### ISSUE TITLE
Peaceful Hunger

### ISSUE THREAD

**Issue by Gavin456b** [mactso/HarderNaturalHealing#1]
Hi, when peaceful hunger is enabled. Eating restores the hunger bar but I do not heal and the next time I am damaged my hunger returns to the value it was at before eating. It seems the game isnt registering that I actually ate. This only occurs on peaceful.

**Comment by Blushymallow** [comment]
I created an account just to bump this as I have the same issue. Unfortunately this is the only mod that does what I need for 1.16.5, so I'd really appreciate it if the issue could be fixed. Thank you!

**Comment by mactso** [comment]
Hi Guys,
Thanks for creating the issue.  I worked it under another ticket and put in a fix for this last week.
Please let me know if you have still have a problem.  Otherwise, I'll close this ticket in 7 days.

**Comment by mactso** [comment]
No further activity.  Issue looks fixed.  Closing.
