### ISSUE TITLE
Console Is filled with debug info.

### ISSUE THREAD

**Issue by Vexllith** [mactso/HarderNaturalHealing#2]
Console Is filled with debug info despite the debug config set to 0
![image](https://user-images.githubusercontent.com/48931796/122512670-089a5500-cfbe-11eb-8b9f-ed979afe5770.png)
![image](https://user-images.githubusercontent.com/48931796/122512789-439c8880-cfbe-11eb-9dc1-53308a05b0e9.png)

**Comment by mactso** [comment]
I'll look into this now.  

It looks like I left  level 0 debugging in the mod.  Sorry!

**Comment by mactso** [comment]
Okay, it should be fixed and updated in the next couple hours.

**Comment by mactso** [comment]
This is fixed and retested.  Sorry i missed it.  I'll close this in a few days if I don't hear there's a problem from you.
